### ISSUE TITLE
Tab switching data clearing issue

### ISSUE THREAD

**Issue by LeonCry** [fisschl/pages#1]
When one selects an item in the 'Naming and Translation' tab, the content of the other tab gets **cleared**. It would be nice to keep the original content.

**Comment by fisschl** [comment]
Pages are divided according to functionality, and each part is independent of each other. When switching through navigation, the page should discard the data from the previous page. If you wish to view the data from two pages simultaneously, you should achieve this by using browser tabs. Close.
